@startuml
'https://plantuml.com/sequence-diagram

autonumber

mainframe **sd** Smart charging control loop

actor Developer
participant "CS1:CS" as CS1 <<ChargingStation>>
participant ":CSMS" as CSMS <<ManagementSystem>>

== Initialization ==
Developer ->CSMS: startCSMS
activate CSMS
CSMS->CSMS: boot
CSMS->CSMS: addRequestHandlers
note left: Adds request handler for\n**BootNotificationRequest**.
CSMS->CSMS: startSmartChargingControlLoop
note left: Starts the charging profile control loop internally.

Developer -> CS1: startCS
activate CS1
CS1->CS1: instantiateAPI
CS1->CS1: addRequestHandlers
note left: Adds request handler for\n**SetChargingProfileRequest**.
CS1->CSMS: bootNotificationRequest(csData)
CSMS->CSMS: registerCS
CSMS-->CS1: bootNotificationResponse "OK"

== Repetition ==
group smart charging control loop [until CSMS exits]
    CSMS->CS1: SetChargingProfileRequest(chargingProfile)
    CS1->CS1: handleRequest(chargingProfile)
    CS1-->CSMS: SetChargingProfileResponse "OK"
    CSMS->CSMS: wait(duration)
    note left: **duration = 15 [s]** for demonstration purposes.
end

@enduml