default:
  image: maven:3.8.6-openjdk-11
  services:
    - docker:25.0.3-dind
  before_script:
    - "cd $PROJECT_DIR"

stages:
  - Compile
  - Build
  - Tests
  - Deploy

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - '.m2/repository'

# Environment variables
variables:
  # This will provide the ci_setting.xml file which contains maven settings when deploying packages to the repo.
  # Also, suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  # MAVEN_OPTS is automatically used by Maven.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--settings ../ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  PROJECT_DIR: "digitalenergyhub"
  DOCKER_TLS_CERTDIR: "/certs"

compile:maven:
  stage: Compile
  script:
    - 'mvn $MAVEN_CLI_OPTS clean compile'
  except:
    - /^release/.*$/  # Match release/ branches
    - tags

install:maven:
  stage: Build
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests clean install'

tests:unit:
  stage: Tests
  script:
    # Reference:
    # -am will make all the other sub-modules.
    # -DfailIfNoTests=false does not fail the entire process since we are not intending to run tests in other modules.
    # -Dtest=**/unit/** matches all test classes located within folders named unit.
    - 'mvn $MAVEN_CLI_OPTS test -Dsurefire.failIfNoSpecifiedTests=false -Dtest=**/unit/** -am'

tests:integration:
  stage: Tests
  before_script:
    - 'docker info'
    - 'docker compose version'
    - 'docker compose create -f infrastructure/compose-yml --remove-orphans' # Creates the containers and removes orphans (old unused containers).
    - 'docker compose up -f infrastructure/compose-yml --timestamps --wait --wait-timeout 30' # Spin up integration testing environment
  script:
    # Reference:
    # -am will make all the other sub-modules.
    # -DfailIfNoTests=false does not fail the entire process since we are not intending to run tests in other modules.
    # -Dtest=**/integration/** matches all test classes located within folders named integration.
    - 'mvn $MAVEN_CLI_OPTS test -Dsurefire.failIfNoSpecifiedTests=false -Dtest=**/integration/** -am'

deploy_to_gitlab:
  stage: Deploy
  script: # gitlab-maven refers to a specific server in the settings.xml
    - 'mvn $MAVEN_CLI_OPTS deploy -DskipTests'
  only: # for branch name(s)
    - main