version: "3.8"
services:
  # Middleware messaging using NATS.io
  middleware_messaging:
    image: nats:2.9.25
    container_name: nats-server
    restart: "no"
    # Use the provided configuration file.
    command: -c /container/configs/nats.conf
    ports:
      - "1883:1883" # MQTT support in NATS.io
      - "4222:4222" # For clients
      - "6222:6222" # HTTP management port for information reporting.
      - "8222:8222" # Routing port for clustering
      - "8080:8080" # NATS over WebSockets
    volumes:
      - './configs/nats.conf:/container/configs/nats.conf'
    networks:
      - nats_network

  middleware_messaging_inspector:
    image: ulexxander/nats-inspector:latest
    container_name: nats-inspector
    restart: "no"
    ports:
      - "6223:80" # HTTP management port for information reporting.
    networks:
      - nats_network
    depends_on:
      - middleware_messaging

  # InfluxDB for storing NATS.io messages
  influxdb:
    image: influxdb:2.7.10-alpine
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - nats_network
  # Telegraf is responsible for connecting to NATS.io and feed messages to InfluxDB.
  telegraf:
      image: telegraf:1.32.1-alpine
      depends_on:
        - influxdb
      volumes:
        # Mount for telegraf config
        - ./configs/telegraf.d/empty.conf:/etc/telegraf/telegraf.conf:ro  # Override the default config with an empty config to avoid reporting hardware resource usage.
        # OCPP messages
        - ./configs/telegraf.d/ocpp_requests.conf:/etc/telegraf/telegraf.d/ocpp_requests.conf:ro
        - ./configs/telegraf.d/ocpp_responses.conf:/etc/telegraf/telegraf.d/ocpp_responses.conf:ro
        # AnyLogic data
        - ./configs/telegraf.d/anylogic_meta.conf:/etc/telegraf/telegraf.d/anylogic_meta.conf:ro
      env_file:
        - influxv2.env
      networks:
        - nats_network

networks:
  nats_network:

volumes:
  nats-data:
  influxdbv2:
